### ISSUE TITLE
Problem's Ivan Matlab

### ISSUE THREAD

**Issue by AnaCecilia17** [ThibaudLeclere/ABR#1]
<img width="2048" alt="Captura de pantalla 2019-10-31 a las 12 38 05" src="https://user-images.githubusercontent.com/57174574/67943861-4ffe8280-fbdb-11e9-9ec9-fd04024dc1fa.png">
<img width="2048" alt="Captura de pantalla 2019-10-31 a las 12 39 51" src="https://user-images.githubusercontent.com/57174574/67943980-a10e7680-fbdb-11e9-8e91-e4d12907f4eb.png">
<img width="2048" alt="Captura de pantalla 2019-10-31 a las 12 39 46" src="https://user-images.githubusercontent.com/57174574/67943982-a2d83a00-fbdb-11e9-977a-e4cbc703c911.png">

**Comment by AnaCecilia17** [comment]
i have problems to run the test with the mac :(

**Comment by ThibaudLeclere** [comment]
The problem comes from the fact that Matlab cannot read the text file because the adress is wrong (represented by the variable filename).
So you should either change filename into '19004_izq_abr1.txt', or move the txt file into the parent folder (ABR-master).

**Comment by AnaCecilia17** [comment]
<img width="2048" alt="Captura de pantalla 2019-10-31 a las 13 11 38" src="https://user-images.githubusercontent.com/57174574/67945778-0b291a80-fbe0-11e9-90b3-bf67a189a9e1.png">
You're going to think that im stupid but i got the flie 19004_izq_abr 1.txt into the test units folder and it dosent work, plus i added it ino matlab path and i dont understand that mistake :(

**Comment by AnaCecilia17** [comment]
<img width="2048" alt="Captura de pantalla 2019-10-31 a las 13 42 34" src="https://user-images.githubusercontent.com/57174574/67947617-4e858800-fbe4-11e9-89f3-2e24eec0bd08.png">
i have problems to export the peaks

**Comment by ThibaudLeclere** [comment]
Try with the new version of ABR_GUI. You can dowload this file only from Github.
