### ISSUE TITLE
new issues

### ISSUE THREAD

**Issue by AnaCecilia17** [ThibaudLeclere/ABR#4]
![issue ABR test](https://user-images.githubusercontent.com/57174574/68215783-1d3ffa00-ffe0-11e9-8905-ae5d580ecd4a.jpg)
![issue run test](https://user-images.githubusercontent.com/57174574/68215792-1f09bd80-ffe0-11e9-8134-d095e14ac4a7.jpg)
Even i cant export the data

**Comment by ThibaudLeclere** [comment]
This is because **the current folder must be the folder containing the 'run_TestUnits.m' file**. This will be taken into account and done automatically in further releases.
